id: P003271
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:51:43.046677
source_metadata:
  id: bdr:W19801
  title: མིང་མཛོད།
  author: ''
  volumes:
    84c9d53d64a9438199df70573d505877:
      image_group_id: I1KG1944
      title: ''
      volume_number: 1
      total_pages: 1943
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
