id: P003271
initial_creation_type: ocr
source_metadata:
  id: bdr:W19801
  title: མིང་མཛོད།
  author: ''
  volumes:
    84c9d53d64a9438199df70573d505877:
      image_group_id: I1KG1944
      title: ''
      volume_number: 1
      total_pages: 1943
